### ISSUE TITLE
Legacy extension seems to be broken

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/fuzzpriv#1]
Trying to call fuzzPriv.GC() raises fuzzPriv is undefined and the following error is present at startup:

1522189257927   addons.xpi-utils        WARN    addMetadata: Add-on domfuzz@squarefree.com is invalid: Error: Non-restartless extensions no longer supported (resource://gre/modules/addons/XPIInstall.jsm:531:15) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:531:15

**Comment by jschwartzentruber** [comment]
Should be fixed with 14a3b0a8f68b12af623b46e37be4c4638a267e64. `-fuzzinject` seems broken but I'll look at that later.
