### ISSUE TITLE
Extension cannot not be installed because of incompatibility with Firefox 57.0 Asan build

### ISSUE THREAD

**Issue by ZihanYe** [MozillaSecurity/fuzzpriv#6]
I'm trying to install Fuzzpriv extension on Firefox 57.0 because I want to reproduce some vulnerability that uses functions in Fuzzpriv. However I'm not able to install it. It shows the message below:

<img width="1348" alt="Screenshot 2020-01-21 at 11 31 57" src="https://user-images.githubusercontent.com/23290999/72801655-e02fef00-3c41-11ea-9bde-17450ddd2d80.png">

Do you know how to fix it?

**Comment by jschwartzentruber** [comment]
Did you build it, or download it? Have you set the prefs?

    user_pref("xpinstall.signatures.required", false);
    user_pref("extensions.legacy.enabled", true);

If you are building it, you can also try porting the testcase to use built-in fuzzing functions. Add to mozconfig:

    ac_add_options --enable-fuzzing

And pref:

    user_pref("fuzzing.enabled", true);
    
And then in the testcase, replace `fuzzPriv` calls with:

    FuzzingFunctions.cycleCollect();
    FuzzingFunctions.garbageCollect();

**Comment by ZihanYe** [comment]
@jschwartzentruber , I downloaded the source code from https://ftp.mozilla.org/pub/firefox/releases/ . Yes I have set the prefs. Anyway, the alternative you mentioned works. Thank you!!
